project:
  type: website
  output-dir: docs

website:
  title: "Seung Hyun Kim"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: resume.qmd
        text: CV
      - href: projects.qmd
        text: Projects

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



